### ISSUE TITLE
Lynch syndrome, ICD10=V84.09 is not existed in phemap 1.2

### ISSUE THREAD

**Issue by Shicheng-Guo** [spiros/phemap#1]
I find Lynch syndrome, ICD10=V84.09 is not existed in phemap 1.2. Any idea or suggestion? 
https://phewascatalog.org/phecodes_icd10
Thanks. 
Shicheng

**Comment by spiros** [comment]
hey Shicheng, good point - you should get in touch with the original team that constructed them so they can add it to the core upstream!
